from aiogram.types import FSInputFile
import os

photo_1 = FSInputFile("photo_bot/Высота бедер.jpg")
photo_2 = FSInputFile("photo_bot/Высота груди.jpg")
photo_3 = FSInputFile("photo_bot/Высота переда до талии.jpg")
photo_4 = FSInputFile("photo_bot/Высота сиденья.jpg")
photo_5 = FSInputFile("photo_bot/Длина изделия (низ)(1).jpg")
photo_6 = FSInputFile("photo_bot/Длина изделия (низ).jpg")
photo_7 = FSInputFile("photo_bot/Длина изделия_.jpg")
photo_8 = FSInputFile("photo_bot/Длина спины до талии.jpg")
photo_9 = FSInputFile("photo_bot/Обхват бедер.jpg")
photo_10 = FSInputFile("photo_bot/Обхват груди 1.jpg")
photo_11 = FSInputFile("photo_bot/Ширина спины.jpg")
photo_12 = FSInputFile("photo_bot/Обхват груди 2.jpg")
photo_13 = FSInputFile("photo_bot/Обхват груди 3.jpg")
photo_14 = FSInputFile("photo_bot/Обхват запястья.jpg")
photo_15 = FSInputFile("photo_bot/Обхват плеча.jpg")
photo_16 = FSInputFile("photo_bot/Обхват талии.jpg")
photo_17 = FSInputFile("photo_bot/Обхват шеи.jpg")
photo_18 = FSInputFile("photo_bot/Центр груди.jpg")
photo_19 = FSInputFile("photo_bot/Ширина плеча_.jpg")
photo_20 = FSInputFile("photo_bot/Длина рукава.jpg")
